services:
  frontend:
    image: "$DOCKER_USERNAME/anonymous_quotes_frontend:$TAG"
    container_name: react-frontend
    expose:
      - 80
    networks:
      - webnet
    restart: always

  backend:
    image: "$DOCKER_USERNAME/anonymous_quotes_backend:$TAG"
    container_name: python-backend
    expose:
      - 8000
    networks:
      - webnet
    environment:
      SLACK_WEBHOOK: $SLACK_WEBHOOK
      MINIO_URL: minio.kdidp.art
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_BUCKET_NAME: images
      FONT_PATH: ReenieBeanie-Regular.ttf
    restart: always

networks:
  webnet:
    external: true
  vpn_custom_network:
    external: true
