services:
  frontend:
    image: "$DOCKER_USERNAME/anonymous_quotes_frontend:$TAG"
    container_name: react-frontend
    expose:
      - 80
    networks:
      - quotes-infra_webnet
    restart: always

  backend-core:
    image: "$DOCKER_USERNAME/anonymous_quotes_backend_core:$TAG"
    container_name: python-backend-core
    expose:
      - 8000
    networks:
      - quotes-infra_webnet
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: $MONGO_DB
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
    restart: always

  backend-image-generation:
    image: "$DOCKER_USERNAME/anonymous_quotes_backend_image_generation:$TAG"
    container_name: python-backend-image-generation
    expose:
      - 8000
    networks:
      - quotes-infra_webnet
    environment:
      SLACK_WEBHOOK: $SLACK_WEBHOOK
      MINIO_URL: minio.thewordsleftbehind.com
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_BUCKET_NAME: thumbnails
      FONT_PATH: ReenieBeanie-Regular.ttf
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: $MONGO_DB
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
    restart: always

networks:
  quotes-infra_webnet:
    external: true
  vpn_custom_network:
    external: true
