services:
  frontend-admin:
    image: "$DOCKER_USERNAME/anonymous_quotes_frontend_admin:$TAG"
    container_name: react-frontend-admin
    expose:
      - 80
    networks:
      vpn_custom_network:
        ipv4_address: 10.13.14.99
    restart: always

  backend-admin:
    image: "$DOCKER_USERNAME/anonymous_quotes_backend_admin:$TAG"
    container_name: python-backend-admin
    expose:
      - 8000
    networks:
      vpn_custom_network:
        ipv4_address: 10.13.14.98
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: $MONGO_DB
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
    restart: always

  nginx-admin:
    image: "$DOCKER_USERNAME/nginx-admin:$TAG"
    container_name: nginx-admin
    expose:
      - 80
    volumes:
      - /home/ubuntu/website/logs:/var/log/nginx
      - /home/ubuntu/website/nginx/certificates:/etc/letsencrypt
      - /home/ubuntu/website/nginx/certificates-data:/data/certbot
    networks:
      vpn_custom_network:
        ipv4_address: 10.13.14.10
    restart: always

networks:
  vpn_custom_network:
    external: true
