name: Build Deploy Core App
on:
  push:
    branches: [master]
    paths:
      - 'frontend/**'
      - 'backend-core/**'
      - 'backend-image-generation/**'

jobs:
  # Generate short SHA for all builds to use
  prepare:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.set_output.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set short SHA
        id: set_output
        run: echo "short_sha=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT

  # Build frontend in parallel
  build-frontend:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker TLS Setup + Build Frontend
        run: |
          cp .docker/* .
          chmod +x ./docker-tls-setup.sh
          source docker-tls-setup.sh
          
          cd $GITHUB_WORKSPACE/frontend/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/anonymous_quotes_frontend:${{ needs.prepare.outputs.short_sha }} .
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          KEY_PEM: ${{ secrets.KEY_PEM }}
          CA_PEM: ${{ secrets.CA_PEM }}

  # Build backend-core in parallel
  build-backend-core:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker TLS Setup + Build Backend Core
        run: |
          cp .docker/* .
          chmod +x ./docker-tls-setup.sh
          source docker-tls-setup.sh
          
          cd $GITHUB_WORKSPACE/backend-core/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/anonymous_quotes_backend_core:${{ needs.prepare.outputs.short_sha }} .
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          KEY_PEM: ${{ secrets.KEY_PEM }}
          CA_PEM: ${{ secrets.CA_PEM }}

  # Build backend-image-generation in parallel
  build-backend-image:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker TLS Setup + Build Backend Image Generation
        run: |
          cp .docker/* .
          chmod +x ./docker-tls-setup.sh
          source docker-tls-setup.sh
          
          cd $GITHUB_WORKSPACE/backend-image-generation/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/anonymous_quotes_backend_image_generation:${{ needs.prepare.outputs.short_sha }} .
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          KEY_PEM: ${{ secrets.KEY_PEM }}
          CA_PEM: ${{ secrets.CA_PEM }}

  # Deploy only after all builds complete
  deploy-core:
    runs-on: ubuntu-latest
    needs: [prepare, build-frontend, build-backend-core, build-backend-image]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Docker TLS Setup + Docker Compose
        run: |
          cp .docker/* .
          chmod +x ./docker-tls-setup.sh
          source docker-tls-setup.sh
          docker-compose up -d
          docker restart nginx-gateway
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          KEY_PEM: ${{ secrets.KEY_PEM }}
          CA_PEM: ${{ secrets.CA_PEM }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          TAG: ${{ needs.prepare.outputs.short_sha }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PG_USER: ${{secrets.PG_USER}}
          PG_PASSWORD: ${{secrets.PG_PASSWORD}}
          MINIO_ROOT_PASSWORD: ${{secrets.MINIO_ROOT_PASSWORD}}
          MINIO_ROOT_USER: ${{secrets.MINIO_ROOT_USER}}
          MONGO_DB: ${{secrets.MONGO_INITDB_DATABASE}}
          MONGO_USER: ${{secrets.MONGO_INITDB_ROOT_USERNAME}}
          MONGO_PASSWORD: ${{secrets.MONGO_INITDB_ROOT_PASSWORD}}
