name: Docker Build

on:
  push:
    branches:
      - master # Trigger the build on pushes to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest # Choose the runner environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checkout the repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Set up Docker Buildx for multi-platform builds

      # Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Build and deploy
        run: |
          chmod +x ./docker-tls-setup.sh
          ./docker-tls-setup.sh
          docker build -t ${{ secrets.DOCKER_USERNAME }}/anonymous_quotes_frontend:${{ github.sha }} .
          cd backend/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/anonymous_quotes_backend:${{ github.sha }} .
          docker-compose up -d
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          CERT_PEM: ${{ secrets.CERT_PEM }}
          KEY_PEM: ${{ secrets.KEY_PEM }}
          CA_PEM: ${{ secrets.CA_PEM }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
