name: Pull Request Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or match your project version

      - name: Install dependencies and run lint
        run: |
          npm ci
          npm run lint

      - name: Build Docker Images (no push)
        run: |
          cp .docker/* .
          docker build -t temp/frontend:pr .
          cd backend/
          docker build -t temp/backend:pr .
